package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"testozon/graph/model"
	"testozon/internal/domain"
	"testozon/internal/loader"
	"testozon/internal/repository"
	"testozon/internal/service"
)

// Replies is the resolver for the replies field.
func (r *commentResolver) Replies(ctx context.Context, obj *model.Comment, first int, after *string) (*model.CommentConnection, error) {
	postID, err := parseID("postID", obj.PostID)
	if err != nil {
		return nil, err
	}
	parentID, err := parseID("comment ID", obj.ID)
	if err != nil {
		return nil, err
	}
	commentLoader, err := loader.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	request := pageRequest(first, after)
	page, err := commentLoader.Load(ctx, repository.CommentPageKey{
		PostID: postID, ParentID: parentID, First: request.First, After: request.After,
	})
	if err != nil {
		return nil, err
	}
	return toCommentConnection(page), nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	post, err := r.Service.CreatePost(ctx, service.CreatePostInput{Title: input.Title, Content: input.Content})
	if err != nil {
		return nil, err
	}
	return toPost(post), nil
}

// SetPostCommentsEnabled is the resolver for the setPostCommentsEnabled field.
func (r *mutationResolver) SetPostCommentsEnabled(ctx context.Context, postID string, enabled bool) (*model.Post, error) {
	id, err := parseID("postID", postID)
	if err != nil {
		return nil, err
	}
	post, err := r.Service.SetPostCommentsEnabled(ctx, id, enabled)
	if err != nil {
		return nil, err
	}
	return toPost(post), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	postID, err := parseID("postID", input.PostID)
	if err != nil {
		return nil, err
	}
	parentID, err := parseOptionalID("parentID", input.ParentID)
	if err != nil {
		return nil, err
	}
	comment, err := r.Service.CreateComment(ctx, service.CreateCommentInput{
		PostID:   postID,
		ParentID: parentID,
		Text:     input.Text,
	})
	if err != nil {
		return nil, err
	}
	return toComment(comment), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, first int, after *string) (*model.CommentConnection, error) {
	postID, err := parseID("post ID", obj.ID)
	if err != nil {
		return nil, err
	}
	commentLoader, err := loader.FromContext(ctx)
	if err != nil {
		return nil, err
	}
	request := pageRequest(first, after)
	page, err := commentLoader.Load(ctx, repository.CommentPageKey{
		PostID: postID, Root: true, First: request.First, After: request.After,
	})
	if err != nil {
		return nil, err
	}
	return toCommentConnection(page), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first int, after *string) (*model.PostConnection, error) {
	page, err := r.Service.Posts(ctx, pageRequest(first, after))
	if err != nil {
		return nil, err
	}
	return toPostConnection(page), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	postID, err := parseID("post ID", id)
	if err != nil {
		return nil, err
	}
	post, err := r.Service.Post(ctx, postID)
	if errors.Is(err, domain.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toPost(post), nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	id, err := parseID("postID", postID)
	if err != nil {
		return nil, err
	}
	if _, err := r.Service.Post(ctx, id); err != nil {
		return nil, err
	}

	source := r.Broker.Subscribe(ctx, id)
	comments := make(chan *model.Comment, 1)
	go func() {
		defer close(comments)
		for {
			select {
			case <-ctx.Done():
				return
			case comment, ok := <-source:
				if !ok {
					return
				}
				select {
				case comments <- toComment(comment):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return comments, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	commentResolver      struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	postResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
