// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	ID        string             `json:"id"`
	PostID    string             `json:"postID"`
	ParentID  *string            `json:"parentID,omitempty"`
	AuthorID  string             `json:"authorID"`
	Text      string             `json:"text"`
	CreatedAt time.Time          `json:"createdAt"`
	Replies   *CommentConnection `json:"replies"`
}

type CommentConnection struct {
	Nodes    []*Comment `json:"nodes"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type CreateCommentInput struct {
	PostID   string  `json:"postID"`
	ParentID *string `json:"parentID,omitempty"`
	Text     string  `json:"text"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID              string             `json:"id"`
	AuthorID        string             `json:"authorID"`
	Title           string             `json:"title"`
	Content         string             `json:"content"`
	CommentsEnabled bool               `json:"commentsEnabled"`
	CreatedAt       time.Time          `json:"createdAt"`
	Comments        *CommentConnection `json:"comments"`
}

type PostConnection struct {
	Nodes    []*Post   `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type Query struct {
}

type Subscription struct {
}
